# Generated by Django 5.0.7 on 2024-10-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCambioPrecios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='nombreDeLista',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
