# Generated by Django 5.1.2 on 2024-10-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCambioPrecios', '0002_precio_nombredelista'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioAntiguo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idListaPrecio', models.IntegerField()),
                ('idProducto', models.IntegerField()),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
