# Generated by Django 5.1.2 on 2024-10-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCambioPrecios', '0003_precioantiguo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioantiguo',
            name='idListaPrecio',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='precioantiguo',
            name='idProducto',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='precioantiguo',
            name='precio_anterior',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
