# Generated by Django 5.1.2 on 2024-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCambioPrecios', '0004_alter_precioantiguo_idlistaprecio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precios_Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroCta', models.IntegerField()),
                ('idProducto', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
