# Generated by Django 5.1.2 on 2024-10-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCambioPrecios', '0005_precios_clientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precios_Clientes',
            new_name='PrecioCliente',
        ),
    ]
