# Generated by Django 5.1.2 on 2024-10-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCambioPrecios', '0006_rename_precios_clientes_preciocliente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='precioantiguo',
            unique_together={('idListaPrecio', 'idProducto')},
        ),
    ]
