# Generated by Django 5.1.2 on 2024-10-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCambioPrecios', '0007_alter_precioantiguo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
