# Generated by Django 5.1.2 on 2024-12-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCambioPrecios', '0008_alter_precio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
